name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main  # Deploys on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to IPFS
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'Decentralized Website'
          path: './myweb'
          pinata-api-key: ${{ secrets.PINATAAPIKEY }}
          pinata-secret-api-key: ${{ secrets.PINATASECRETAPIKEY }}
          verbose: true
